add a variable to control whether prefer pyls
emacs-lsp/lsp-python-ms pull request #85
Opened 2020-02-28 03:45 UTC by kevindragon

https://github.com/seagle0128/.emacs.d/issues/156

2020-02-28 04:01 UTC, seagle0128 commented
The proriority is able to select the lsp server. Is there any reason to add a variable for control it? I don't think it's necessary.

2020-02-28 12:31 UTC, kevindragon commented
I did not know how to set priority.

2020-02-28 14:21 UTC, seagle0128 commented
Currently there are two lsp servers for Python: pyls and mspyls. `pyls` is builtin of `lsp-mode` and it has higher priority. `mspyls` is implemented by C# and it's faster, but it's not the default one. 

If `pyls` is not installed, lsp-mode will try to use `mspyls` if `lsp-pyton-ms` is loaded.

2020-03-01 03:13 UTC, kevindragon commented
如果我希望使用`pyls`就没有必要安装`lsp-python-ms`这个包了。既然我安装了`lsp-python-ms`，但是默认又不启动，这个行为我觉得不是太好。我之前安装的201912XX版本是默认启动的，我升级后花了两个小时来检查哪里出了问题（可能是我对lsp-mode以及lsp-python-ms的源代码不熟悉）。
所以我觉得既然安装了`lsp-python-ms`这个包，就应该默认开启，如果不需要，uninstall就可以了。

2020-05-15 04:37 UTC, seagle0128 requested changes

2020-05-15 04:37 UTC, seagle0128 commented on lsp-python-ms.el
> +(defvar lsp-python-ms-prefer-pyls
Should use `defcustom`.

2020-05-15 04:37 UTC, seagle0128 commented on README.org
> +For now, the pyls is the default lsp client (priority of lsp-python-ms is set to -2), If you prefer lsp-python-ms, please set =lsp-python-ms-prefer-pyls= to =nil=.
or uninstall `pyls`?

2020-05-19 02:08 UTC, closed without merging

2020-05-19 02:10 UTC, seagle0128 commented
Add a new option `lsp-python-ms-auto-install-server` to handle this case.